#auto: true
safe: false
#include: ./pages/
plugins:
  - ./_plugins/category_nav.rb
  - ./_plugins/CfeLiquidUtils.rb
  - ./_plugins/cfengineAddons.rb
  - ./_plugins/CfeUtils.rb
  - ./_plugins/debug.rb
  - ./_plugins/gentagspages.rb
  - ./_plugins/jekyll_asset_pipeline.rb
  - ./_plugins/navigation.rb
  - ./_plugins/redcarpet2_markdown.rb
  - ./_plugins/references.rb
  - ./_plugins/sitemap_generator.rb
# baseurl: /docs/master/
git-repository: github.com/cfengine/documentation
git-branch: "3.23"
#source:      ./pages/
#destination:
#layouts:     ./_layouts/
#permalink: /:title.html

#CFEngine addon
# CFE_OUTPUT turn on special rules for output, see step2.txt about jekyll core hack (https://github.com/cfengine/documentation/blob/master/generator/_setup/step2.txt)
CFE_OUTPUT: true

#CFE_DIR - output folder if CFE_OUTPUT turned on
CFE_DIR: _site
#to create correct links in sitemap
CFE_manuals_version: "3.23"
cfengine:
  branch: "3.23"
  core_branch: "3.23"
  latest_patch_release: 0
  latest_package_build: 1
  vagrant_package_build: 1
  masterfiles_branch: "3.23.x"

Template:
  parse:
    line_numbers: true

vagrant:
  version: "2.2.19"

virtualbox:
  version: "6.1.38"

paginate: 500

pygments: true
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: docs/master/assets       # Default = nil
  gzip: false             # Default = false
